// <auto-generated />
using DemoVolApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoVolApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20220105204534_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("DemoVolApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "James Bond",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Title = "Untamed",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Title = "Azure Developer",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
